---
- name: Ensure a directory for Dockerfile for building image exists
  file:
    path: "{{ c_temp_dir }}/docker/build"
    state: directory

- name: Templating Dockerfile for building image
  template:
    src: "{{ role_path }}/files/Dockerfile.j2"
    dest: "{{ c_temp_dir }}/docker/build/Dockerfile"

- name: Ensure building docker image is built
  docker_image:
    name: "img_{{ c_app_name }}_build"
    source: build
    build:
      path: "{{ c_temp_dir }}/docker/build"
    force_source: yes
    state: present

- name: Ensure building docker container is created and running
  docker_container:
    name: "{{ c_app_name }}_build"
    image: "img_{{ c_app_name }}_build"
    state: present
    recreate: yes
    force_kill: yes
    volumes:
      - "{{ c_temp_dir }}/{{ c_app_name }}:{{ c_build_path }}/target:rw"
  notify: Fetch the app package
