---
- name: Ensure a directory for Dockerfile for prod image exists
  file:
    path: "{{ c_temp_dir }}/docker/prod"
    state: directory

- name: Templating Dockerfile for prod image
  template:
    src: "{{ role_path }}/files/Dockerfile.j2"
    dest: "{{ c_temp_dir }}/docker/prod/Dockerfile"

- name: Ensure building docker image is built
  docker_image:
    name: "img_{{ c_app_name }}_prod"
    source: build
    build:
      path: "{{ c_temp_dir }}/docker/prod"
    force_source: yes
    state: present

- name: Ensure a directory for mount point for docker volume exists
  file:
    path: "{{ c_temp_dir }}/{{ c_app_name }}"
    state: directory

- name: Ensure building docker container is created and running
  docker_container:
    name: "{{ c_app_name }}_prod"
    image: "img_{{ c_app_name }}_prod"
    state: started
    recreate: yes
    force_kill: yes
    mounts:
      - target: "{{ c_tomcat_base }}/webapps"
        source: "{{ c_temp_dir }}/{{ c_app_name }}"
        type: bind
        read_only: no
    network_mode: bridge
    ports:
      - "8081:{{ c_tomcat_port }}"
  notify: Ensure the app package is installed
