---
- name: Ensure the app package is installed
  synchronize:
    src: "{{ c_temp_dir }}/{{ c_app_name }}.war"
    dest: "{{ c_temp_dir }}/{{ c_app_name }}/{{ c_app_name }}.war"
    mode: push
