---
- name: Ensure docker emvironment is set up and running
  hosts: docker
  become: yes
  
  tasks:
  - name: Ensure an apt key for docker rep is present
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /etc/apt/keyrings/docker.gpg
  
  - name: Ensure a docker repository is in reps list
    apt_repository:
      repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable
      state: present
      filename: docker
  
  - name: Ensure docker-ce package is present
    apt:
      name: docker-ce
      state: present
      update_cache: yes

  - name: Ensure docker-ce package is present
    apt:
      name: docker-ce
      state: present
      
  - name: Ensure docker-ce-cli package is present
    apt:
      name: docker-ce-cli
      state: present

  - name: Ensure containerd.io package is present
    apt:
      name: containerd.io
      state: present
      autoclean: yes
      autoremove: yes
  
  - name: Ensure docker-compose executable is present
    get_url:
      url: https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64
      dest: /bin/docker-compose
      mode: +x