---
- name: Ensure docker emvironment is set up and running
  hosts: docker
  become: yes
  
  tasks:
  - name: Ensure an apt key for docker rep is present
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /etc/apt/keyrings/docker.gpg
  
  - name: Ensure a docker repository is in reps list
    apt_repository:
      repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable
      state: present
      filename: docker
  
  - name: Ensure docker-ce package is present
    apt:
      name: docker-ce
      state: present
      update_cache: yes

  - name: Ensure docker-ce package is present
    apt:
      name: docker-ce
      state: present
      
  - name: Ensure docker-ce-cli package is present
    apt:
      name: docker-ce-cli
      state: present

  - name: Ensure containerd.io package is present
    apt:
      name: containerd.io
      state: present
      autoclean: yes
      autoremove: yes
  
  - name: Ensure docker-compose executable is present
    get_url:
      url: https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64
      dest: /bin/docker-compose
      mode: +x
  
  - name: Ensure docker daemon is set up properly (stage 1)
    copy:
      src: docker_override.conf
      dest: /etc/systemd/system/docker.service.d/override.conf

  - name: Ensure docker daemon is set up properly (stage 2)
    systemd:
      name: docker
      state: reloaded
      daemon_reload: yes

  - name: Ensure git package is present
    apt:
      name: git
      state: present
      update_cache: yes
      autoclean: yes
      autoremove: yes

  - name: Ensure app repository is up to date
    git:
      dest: /tmp/java_app
      force: yes
      repo: https://github.com/slayhammer/study_ansible_1.git

  - name: Ensure app built and running
    docker_compose:
      project_src: /tmp/java_app/study_ansible_1/java_app_dockerd
      build: yes
      state: present
