---
- name: Ensure tomcat package is present
  apt:
    name: tomcat9
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Ensure tomcat is running
  service:
    name: tomcat9
    state: started
  
- name: Ensure the app package is installed
  synchronize:
    src: "{{ c_temp_dir }}/{{ c_app_name }}.war"
    dest: "{{ c_tomcat_webapps }}/{{ c_app_name }}.war"
    mode: push
