---
- name: Building the app
  hosts: setup
  become: yes
  
  # 'run_mode' variable MUST BE defined at INVENTORY level
  # and HAVE TO have a value either 'dockerd' (in case of docker mode)
  #                          or     some other, eg. 'hosted' (in case of hosted mode)
  roles:
    - role: build-hosted
      when: run_mode != 'dockerd'
    - role: build-dockerd
      when: run_mode == 'dockerd'

- name: Deploying the app
  hosts: prod
  become: yes
  
  roles:
    - role: prod-hosted
      when: run_mode != 'dockerd'
    - role: prod-dockerd
      when: run_mode == 'dockerd'
