---
- name: install nginx
  hosts: web
  become: yes

  tasks:
  - name: Ensure nginx packages is present
    apt:
      name: nginx
      state: present

  - name: Ensure nginx service is started
    service:
      name: nginx
      state: started

  - name: Ensure index.html contain date string
    lineinfile:
      path: /var/www/html/index.nginx-debian.html
      line: '<p><script> document.write(new Date().toLocaleDateString()); </script></p>'
      insertafter: '<h1>Welcome to nginx!</h1>'
