# This is a sample java app setup package (https://github.com/ashburnere/onlineshop-war)
# wrapped in a docker container.

# Based on 'ubuntu' ver. 20.04 Official Docker Image
FROM ubuntu:20.04

# Environment setup
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow
RUN mkdir /tmp/mount_point

# Seting up all necessary software and further cache cleaning:
#	'git'         - for cloning the sample java app from a rep
#	'maven'       - for building the app
RUN apt-get update && apt-get install -y \
	git \
	maven \
	&& rm -rf /var/lib/apt/lists/*	

# Fetching the sample java app src
RUN git clone {{ c_app_repo }} {{ c_build_path }}

# Building the app
RUN mvn package -f {{ c_build_path }}

# Copying an artifact to binded volume
CMD "cp -f {{ c_build_path }}/target/{{ c_app_name }}.war {{ c_mount_point }}/{{ c_app_name }}.war"
