---
- vars:
    c-app-repo: https://github.com/ashburnere/onlineshop-war.git
    c-build-path: /tmp/onlineshop-war
    c-tomcat-webapps: /var/lib/tomcat9/webapps
    c-temp-dir: /tmp
    c-app-name: onlineshop.war


- name: Building an java app
  hosts: setup
  become: yes
  
  tasks:
  - name: Ensure required packages are present
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
      autoclean: yes
      autoremove: yes
    with_items:
      - git
      - maven
  
  - name: Ensure the package is built from the latest code in the repository
    git:
      dest: "{{ c-build-path }}"
      force: yes
      repo: "{{ c-app-repo }}"
      notify: Build app package (imperative)
  
  - name: Fetch the app package
    synchronize:
      src: "{{ c-build-path }}/target/{{ c-app-name }}"
      dest: "{{ c-temp-dir }}/{{ c-app-name }}"
      mode: pull

  Handlers:
    - name: Build app package (imperative)
      shell:
        cmd: "mvn package -f {{ c-build-path }}"

- name: Run an java app
  hosts: prod
  become: yes

  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present
      update_cache: yes
      autoclean: yes
      autoremove: yes
  
  - name: Ensure tomcat is running
    service:
      name: tomcat9
      state: started
  
  - name: Ensure the app package is installed
    synchronize:
      src: "{{ c-temp-dir }}/{{ c-app-name }}"
      dest: "{{ c-tomcat-webapps }}/{{ c-app-name }}"
      mode: push
