---
- name: Building an java app
  hosts: setup
  become: yes
  
  tasks:
  - name: Ensure git package is present
    apt:
      name: git
      state: present
      update_cache: yes
  
  - name: Ensure maven package is present
    apt:
      name: maven
      state: present
      autoclean: yes
      autoremove: yes
  
  - name: Ensure app repository is up to date
    git:
      dest: /tmp/onlineshop-war
      force: yes
      repo: https://github.com/ashburnere/onlineshop-war.git
  
  - name: Build app package (imperative)
    shell:
      cmd: mvn package -f /tmp/onlineshop-war
  
  - name: Ensure app package is built
    file:
      path: /tmp/onlineshop-war/target/onlineshop.war
      state: file

  - name: Fetch the app package
    fetch:
      src: /tmp/onlineshop-war/target/onlineshop.war
      dest: /tmp/onlineshop.war

- name: Run an java app
  hosts: prod
  become: yes

  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present
      update_cache: yes
      autoclean: yes
      autoremove: yes
  
  - name: Ensure tomcat is running
    service:
      name: tomcat9
      state: started
  
  - name: Ensure the app package is installed
    copy:
      src: /tmp/onlineshop.war
      dest: /var/lib/tomcat9/webapps/onlineshop.war
      