---
- name: Building an java app
  hosts: setup
  become: yes
  vars_files:
    - ./java-app-vars.yml
  
  tasks:
    - name: Ensure required packages are present
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        autoclean: yes
        autoremove: yes
      with_items:
        - git
        - maven

    - name: Ensure the package is built from the latest code in the repository
      git:
        dest: "{{ c_build_path }}"
        force: yes
        repo: "{{ c_app_repo }}"
      notify: Build app package (imperative)

    - name: Fetch the app package
      synchronize:
        src: "{{ c_build_path }}/target/{{ c_app_name }}"
        dest: "{{ c_temp_dir }}/{{ c_app_name }}"
        mode: pull

  handlers:
    - name: Build app package (imperative)
      shell:
        cmd: "mvn package -f {{ c_build_path }}"

- name: Run an java app
  hosts: prod
  become: yes
  vars_files:
    - ./java-app-vars.yml

  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present
      update_cache: yes
      autoclean: yes
      autoremove: yes
  
  - name: Ensure tomcat is running
    service:
      name: tomcat9
      state: started
  
  - name: Ensure the app package is installed
    synchronize:
      src: "{{ c_temp_dir }}/{{ c_app_name }}"
      dest: "{{ c_tomcat_webapps }}/{{ c_app_name }}"
      mode: push
